<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />
	
</head>

<body>
	
	<!-- 一览图 -->
	<!-- map1Page start  -->
	<div data-role="page" id="map1Page">	

		<div data-role="header" class="header_1 bg41AC98">
			<a data-transition="slide" href="#" data-role="button"
				data-rel="back" class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>
			<h1 class="colorFFF">水贝一览图</h1>
		</div>
		<!-- /header -->
		<div data-role="content">
			<div class="wrapper top">
				<div class="scroller">
					<div class="map1">
						<!-- 
						<a  data-transition="none" href="${pageContext.request.contextPath}/map/map2Page"><img alt=""
							src="${pageContext.request.contextPath}/images/tmp/map_1.jpg"></a>
						<h3>点击字母直接查看板块地图的大图</h3>
						 -->
						<div id="map1PageMap" style="height:500px;width:100%;"></div>
					</div>
					<textarea rows="1" cols="1" id="ringlist" style="display:none;">${ringlist}</textarea>
				</div>
			</div>
		</div>
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d">
			<c:import url="../footer.jsp"/>
		</div>
		
	</div>
	<!-- map1Page end  -->


</body>
</html>