<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
<!-- 楼层列表(水牌) -->
	<!-- map3Page start  -->
	<div data-role="page" id="map3Page">
		
		<div data-role="header" class="header_1">
			<a  data-transition="slide" href="#" data-role="button" data-rel="back"
				class="back" data-icon="arrow-l">&nbsp;</a>
			<h1 class="h">
				<span class="s1">水北街珠宝商厦</span>
				<a  href="#">商家信誉</a>
				<a  href="#">楼层</a>
				<a  href="${pageContext.request.contextPath}/map/map4Page" data-role="none"><span class="color41AC98">示意图</span></a>
			</h1>
		</div>
		
		<div data-role="content">
			<div class="wrapper top">
				<div class="scroller">	
		
					<div class="boxList">
						<div class="box">
							<h3>
								<a  href="#shop1Page">水贝中瑞宝石有限公司</a>
							</h3>
							<h6>深圳市<span class="color41AC98">水贝街珠宝商厦</span>7-2</h6>
							<p class="p1">
								<span>主营产品:</span><span>水晶饰品;天然水晶首饰;天然珠宝</span>
							</p>
							<div class="line"></div>
							<p class="p2">
								<span class="s1">965</span> <span>件产品</span> | <span class="s2">&nbsp;</span> <span class="s3">236</span> <span>次</span>
								<span class="s4 star2">&nbsp;</span>
							</p>
						</div>
						<div class="box">
							<h3>
								<a  href="#shop1Page">金丽中瑞国际珠宝交易中心</a>
							</h3>
							<h6>深圳市<span class="color41AC98">水贝街珠宝商厦</span>7-2</h6>
							<p class="p1">
								<span>主营产品:</span><span>水晶饰品;天然水晶首饰;天然珠宝</span>
							</p>
							<div class="line"></div>
							<p class="p2">
								<span class="s1">965</span> <span>件产品</span> | <span class="s2">&nbsp;</span> <span class="s3">236</span> <span>次</span>
								<span class="s4 star2">&nbsp;</span>
							</p>
						</div>
						<div class="box">
							<h3>
								<a  href="#shop1Page">万山中瑞珠宝有限公司</a>
							</h3>
							<h6>深圳市<span class="color41AC98">水贝街珠宝商厦</span>7-2</h6>
							<p class="p1">
								<span>主营产品:</span><span>水晶饰品;天然水晶首饰;天然珠宝</span>
							</p>
							<div class="line"></div>
							<p class="p2">
								<span class="s1">965</span> <span>件产品</span> | <span class="s2">&nbsp;</span> <span class="s3">236</span> <span>次</span>
								<span class="s4 star2">&nbsp;</span>
							</p>
						</div>
						<div class="box">
							<h3>
								<a  href="#shop1Page">瑞丰银泰<span class="color41AC98">中瑞</span>美珠有限公司</a>
							</h3>
							<h6>深圳市<span class="color41AC98">水贝街珠宝商厦</span>7-2</h6>
							<p class="p1">
								<span>主营产品:</span><span>水晶饰品;天然水晶首饰;天然珠宝</span>
							</p>
							<div class="line"></div>
							<p class="p2">
								<span class="s1">965</span> <span>件产品</span> | <span class="s2">&nbsp;</span> <span class="s3">236</span> <span>次</span>
								<span class="s4 star2">&nbsp;</span>
							</p>
						</div>
					</div>

				</div>
			</div>

		</div>
		
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d">
			<c:import url="../footer.jsp"/>
		</div>
	</div>
	<!-- map3Page end  -->

</body>
</html>