<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
		<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
		<title>Single-Page Application</title>
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

	<script type="text/javascript">
		contextPath = '${pageContext.request.contextPath}';
	</script>		
		
	</head>
	<body>
		<!-- scat1Page 购物车页面 start  -->
		<div data-role="page" id="cartPage">
			<div data-role="header" class="header_1 bg41AC98">
				<a data-transition="slide" href="#" data-role="button" data-rel="back" class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>
				<h1 class="colorFFF">购物车</h1>
				<a data-transition="none" id="cartEditBtn" href="#" data-role="button" class="back bg41AC98 colorFFF">编辑</a>
			</div>
			<!-- /header -->
			<div data-role="content">
				<div class="wrapper top">
					<div class="scroller">
					
						<div id="pullDown">
							<span class="pullDownIcon"></span><span class="pullDownLabel">下拉刷新...</span>
						</div>
					
						<c:import url="./cartAjax.jsp" />
					
					
					</div>
				</div>
			</div>
			<div data-role="footer" data-tap-toggle="false" data-cacheval="false" data-position="fixed" data-theme="d" style="border-top:none;">
				<div class="cartMenu">
					<div class="left ">
						<input type="checkbox" id="carCheckAll" data-role="none" />
					</div>
					<div class="right">
						<div class="cartEdit">
							<a data-transition="none" href="#" data-role="button">移致收藏</a> <a data-transition="none" id="delCartBtn" href="#" data-role="button">删除</a>
						</div>
						<div class="cartNormal">
							<a data-transition="slide" id="cartConfirmOrder" href="#" data-role="button">结算</a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
				<c:import url="../footer.jsp"/>
			</div>
		</div>
		<!-- scat1Page end  -->
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/iscroll/iscroll.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>
	</body>
</html>
