<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
		<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
		<title>Single-Page Application</title>
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />
	</head>
	<body>
		<!-- scat1Page 购物车页面 start  -->
		<div data-role="page" id="cartPage">
			<div data-role="header" class="header_1 bg41AC98">
				<a data-transition="slide" href="#" data-role="button" data-rel="back" class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>
				<h1 class="colorFFF">购物车</h1>
				<a data-transition="none" id="cartEditBtn" href="#" data-role="button" class="back bg41AC98 colorFFF">编辑</a>
			</div>
			<!-- /header -->
			<div data-role="content">
				<div class="wrapper top">
					<div class="scroller">
						<div class="cart">
							<div id="preferential" data-role="popup" data-theme="a">
								<div style="width:300px;overflow:hidden;">
									<h3>优惠说明</h3>
									<hr class="line">
									<p>单笔订单满10000元，返回样品费</p>
									<p>单笔订单满10000元，返回样品费</p>
									<p>单笔订单满10000元，返回样品费</p>
								</div>
							</div>
							<c:forEach items="${cart.cartItems}" var="item">
								<div class="shopBox">
									<div class="title">
										<div class="check">
											<input type="checkbox" name="carShopCheck" data-cacheval="false" data-role="none">
										</div>
										<a class="a1" data-transition="slide" href="${pageContext.request.contextPath}/shop/showShop?id=${item.key.id}">${item.key.cname}</a>
										<a class="a2" data-transition="none" href="#preferential" data-rel="popup" data-position-to="window">优惠说明</a>
									</div>
									<c:forEach items="${item.value}" var="item1">
										<div class="commodity" id="commodity_${item1.sku}">
											<div class="check">
												<input value="${item1.sku}" type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
											</div>
											<div class="box">
												<div class="c_info">
													<div class="c_img">
														<a data-transition="slide" href="${pageContext.request.contextPath}/commodity/show?id=${item1.c.id}"> <img width="53" alt="" src="${pageContext.request.contextPath}/${item1.c.img}">
														</a>
													</div>
													<div class="c_infobox c_skuBox_${item1.sku}">
														<div class="c_title">
															<a data-transition="slide" href="${pageContext.request.contextPath}/commodity/show?id=${item1.c.id}">${item1.c.name}</a>
														</div>
														<div class="c_price">
															<p>
																<span>${item1.c.attr1.name}  </span><span class="s_1">${item1.c.attr1Value}</span> <span>${item1.c.attr2.name}  </span><span class="s_2">${item1.c.attr2Value}</span>
															</p>
															<p>
																<span class="s_3 red">￥ ${item1.c.marketPrice} </span><span class="s_4">x ${item1.buyNum}</span>
															</p>
														</div>
													</div>
													<div class="c_infoboxEdit">
														<div class="number inventoryShowBox">
															<!-- 库存信息 -->
															<c:forEach items="${item1.c.inventoryMap}" var="item2">
																<input type="hidden" value="${item2.value}" name="${item2.key}" />
															</c:forEach>
															<a href="#" class="a1 revNum" sku="${item1.sku}"></a> <input sku="${item1.sku}" name="buyNum" class="input buyNum" type="number" data-role="none" value="1" /> <a sku="${item1.sku}" href="#" class="a2 addNum"></a>
														</div>
														<p class="p2">
															<a id="attrShowBtn_${item1.sku}" class="cartPopupBtn" data-rel="popup" data-position-to="window"  data-transition="pop" href="#addCartPopup${item1.sku}">${item1.c.attr1.name}:${item1.c.attr1Value};${item1.c.attr2.name}:${item1.c.attr2Value}</a>
														</p>
														<div id="addCartPopup${item1.sku}" data-role="popup" class="popupBox" data-transition="pop">
															<a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right"> Close</a>
															<div class="popup">
																<form action="${pageContext.request.contextPath}/buy/addCart" class="cartForm" method="post" data-transition="slide">
																	<input type="hidden" name="_stype" value="ajax">
																	<div class="box">
																		<div class="img">
																			<img alt="" src="${pageContext.request.contextPath}/${item1.c.img}">
																		</div>
																		<div class="info inventoryShowBox">
																			<span class="s1">￥${item1.c.marketPrice}</span> 
																			<span class="s2">库存 <strong class="inventoryNum"></strong> 件</span> 
																			<span class="s3">已选 <span class="attr1ValShow">请选择</span> <span class="attr2ValShow"></span></span> 
																			<input type="hidden" value="${item1.c.id}" name="cid" /> 
																			<input type="hidden" value="" id="buyTypeHid" /> 
																			<input type="hidden" value="1" name="buyNum" />
																			<input type="hidden" value="${item1.sku}" name="sku" />
																			<input type="hidden" class="attr1Val" name="attr1Val" tit="${item1.c.attr1.name}" value="" /> 
																			<input type="hidden" class="attr2Val" name="attr2Val" tit="${item1.c.attr2.name}" value="" />
																		</div>
																	</div>
																	<div class="line"></div>
																	<div class="box">
																		<span class="title">${item1.c.attr1.name}</span>
																		<div class="attr1">
																			<c:forEach items="${item1.c.attr1List}" var="item6" varStatus="status">
																				<a class="choseAttr1" aid="${item6[0]}" href="#">${item6[1]}</a>
																			</c:forEach>
																		</div>
																	</div>
																	<div class="line"></div>
																	<div class="box">
																		<span class="title">${item1.c.attr2.name}</span>
																		<div class="attr2">
																			<c:forEach items="${item1.c.attr2List}" var="item6" varStatus="status">
																				<a class="choseAttr2" aid="${item6[0]}" href="#">${item6[1]}</a>
																			</c:forEach>
																		</div>
																	</div>
																	<div class="line"></div>
																	<div class="buyBtn">
																		<a sku="${item1.sku}" class="confirmCommodityBtn a1" href="#">确定</a>
																	</div>
																</form>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</c:forEach>
								</div>
							</c:forEach>
							<!-- 
							<div class="shopBox">
								<div class="title">
									<div class="check">
										<input type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
									</div>
									<a class="a1" href="#">深圳市大本钟贸易有限...</a> 
									<a class="a2" data-transition="none" href="#preferential" data-rel="popup" data-position-to="window">优惠说明</a>
								</div>
	
								<div class="commodity">
									<div class="check">
										<input type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
									</div>
									<div class="box">
										<div class="c_info">
											<div class="c_img">
												<img width="53" alt=""
													src="${pageContext.request.contextPath}/images/commodity/c_4.jpg">
											</div>
											<div class="c_infobox">
												<div class="c_title">【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</div>
												<div class="c_price">
													<p>
														<span>克数:</span><span class="s_1">100</span> <span>手寸:</span><span
															class="s_2">2x2</span>
													</p>
													<p>
														<span class="s_3">$123123 </span><span class="s_4">x 1</span>
													</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								
								<div class="commodity">
									<div class="check">
										<input type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
									</div>
									<div class="box">
										<div class="c_info">
											<div class="c_img">
												<img width="53" alt=""
													src="${pageContext.request.contextPath}/images/commodity/c_4.jpg">
											</div>
											<div class="c_infobox">
												<div class="c_title">【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</div>
												<div class="c_price">
													<p>
														<span>克数:</span><span class="s_1">100</span> <span>手寸:</span><span
															class="s_2">2x2</span>
													</p>
													<p>
														<span class="s_3">$123123 </span><span class="s_4">x 1</span>
													</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								
							</div>
							
							
							<div class="shopBox">
								<div class="title">
									<div class="check">
										<input type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
									</div>
									<a class="a1" href="#">深圳市大本钟贸易有限...</a> 
									<a class="a2" data-transition="none" href="#preferential" data-rel="popup" data-position-to="window">优惠说明</a>
								</div>
	
								<div class="commodity">
									<div class="check">
										<input type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
									</div>
									<div class="box">
										<div class="c_info">
											<div class="c_img">
												<img width="53" alt=""
													src="${pageContext.request.contextPath}/images/commodity/c_4.jpg">
											</div>
											<div class="c_infobox">
												<div class="c_title">【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</div>
												<div class="c_price">
													<p>
														<span>克数:</span><span class="s_1">100</span> <span>手寸:</span><span
															class="s_2">2x2</span>
													</p>
													<p>
														<span class="s_3">$123123 </span><span class="s_4">x 1</span>
													</p>
												</div>
											</div>
										</div>
									</div>
								</div>
	
								<div class="commodity">
									<div class="check">
										<input type="checkbox" name="carCheck" data-cacheval="false" data-role="none">
									</div>
									<div class="box">
										<div class="c_info">
											<div class="c_img">
												<img width="53" alt=""
													src="${pageContext.request.contextPath}/images/commodity/c_4.jpg">
											</div>
											<div class="c_infobox">
												<div class="c_title">【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</div>
												<div class="c_price">
													<p>
														<span>克数:</span><span class="s_1">100</span> <span>手寸:</span><span
															class="s_2">2x2</span>
													</p>
													<p>
														<span class="s_3">$123123 </span><span class="s_4">x 1</span>
													</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								
							</div>
							
							 -->
						</div>
					</div>
				</div>
			</div>
			<div data-role="footer" data-tap-toggle="false" data-cacheval="false" data-position="fixed" data-theme="d" style="border-top:none;">
				<div class="cartMenu">
					<div class="left ">
						<input type="checkbox" id="carCheckAll" data-role="none" />
					</div>
					<div class="right">
						<div class="cartEdit">
							<a data-transition="none" href="#" data-role="button">移致收藏</a> <a data-transition="none" id="delCartBtn" href="#" data-role="button">删除</a>
						</div>
						<div class="cartNormal">
							<a data-transition="slide" id="cartConfirmOrder" href="#" data-role="button">结算</a>
						</div>
					</div>
					<div class="clear"></div>
				</div>
				<div data-role="navbar" class="myfooter bgEDEDED">
					<ul>
						<li><a data-transition="none" href="${pageContext.request.contextPath}/main" class="ui-icon-index_1 ui-btn-active1">首页</a></li>
						<li><a data-transition="none" href="${pageContext.request.contextPath}/map/map1Page" class="ui-icon-map_1">地图</a></li>
						<li><a data-transition="none" href="${pageContext.request.contextPath}/buy/cart" class="ui-icon-purchase_1">进货单</a></li>
						<li><a data-transition="none" href="${pageContext.request.contextPath}/user/userCenter" class="ui-icon-my_1">我的</a></li>
					</ul>
				</div>
			</div>
		</div>
		<!-- scat1Page end  -->
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/iscroll/iscroll.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
		<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>
	</body>
</html>
