<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %> 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>

</head>

<body>
		<div data-role="page" id="charMessagePage">
			<div data-role="header" class="header_1 bg41AC98">
				<a data-transition="slide" href="#" data-role="button" data-rel="back" class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>
				<h1 class="colorFFF">客服对话</h1>
			</div>
			<div data-role="content">
				<div class="wrapper top">
					<div class="scroller">
						<input type="hidden" name="sid" value="${sid}">
						<input type="hidden" name="uid" value="${uid}">
						<input type="hidden" name="icurrentPage" value="1">
						<div id="pullDown">
							<span class="pullDownIcon"></span><span class="pullDownLabel">下拉刷新...</span>
						</div>
						<div class="msgBox">
							<!-- 
							<div class="msg">
								<div class="u_msg">
									<div class="u_out">
										sdf
									</div>
								</div>
								<div class="u_img"><img alt="" src="${pageContext.request.contextPath}/images/user/auction_1_r6_c6.jpg"></div>
								<div class="clear"></div>				
							</div>
							<div class="msg">
								<div class="u_msg">
									<div class="u_out">
										接到投诉后，长宁区市场监督管理局22日前往荣新馆开展检查，并进行了食品的取样封存、检测。“因为是自助餐，菜品比较多，再加上消费者也说不清具体怀疑什么菜品有问题，我们对于高风险的生食进行了抽样，包括三文鱼、海胆、金枪鱼、海螺、牡丹虾等，送往长宁区食药监检测。鉴定报告通常在送检的7个工作日后出具。”
									</div>
								</div>
								<div class="u_img"><img alt="" src="${pageContext.request.contextPath}/images/user/auction_1_r6_c6.jpg"></div>
								<div class="clear"></div>				
							</div>
							<div class="msg">
								<div class="u_msg">
									<div class="u_out">
										
									</div>
								</div>
								<div class="u_img"><img alt="" src="${pageContext.request.contextPath}/images/user/auction_1_r6_c6.jpg"></div>
								<div class="clear"></div>				
							</div>
							 -->
						</div>
						
					</div>
				</div>
			</div>
			<div data-role="footer" data-tap-toggle="false" data-cacheval="false" data-position="fixed" data-theme="d" style="border-top:none;">
				<div class="sendMsgBox">
					<a href="#" class="a1"></a>
					<input name="inputMsg" type="text" class="input1" />
					<a href="#" class="a2" id="sendMsg">发送</a>
				</div>			
				<c:import url="../footer.jsp"/>
			</div>			
		</div>
	
</body>
</html>