<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />
</head>

<body>
	


	<!-- 商家列表 搜索列表 -->
	<!-- sellerListPage start-->
	<div data-role="page" id="sellerListPage" data-dom-cache="true">
		<div data-role="header" class="header_1" data-tap-toggle="false" data-position="fixed">
			
				<a data-transition="slide" href="#" data-role="button" data-rel="back"
					class="back" data-icon="arrow-l">&nbsp;</a>
				<h1 class="h0">
				<form action="${pageContext.request.contextPath}/shop/list" method="get" id="sellerListPage_form">
					<input type="search" name="k" id="sellerListPage_search_k" placeholder="店铺名称" value="${k}">
					<input type="hidden" name="icurrentPage" id="sellerListPage_currentPage" value="1">
					<input type="hidden" name="sort" id="sellerListPage_score" value="${sort}">
					<input type="hidden" name="sortType" id="sellerListPage_scoreType" value="${sortType}">
					<input type="hidden" name="stype" id="sellerListPage_stype" value="${stype}">
					<input type="hidden" name="totalPage" id="totalPage" value="${totalPage}">
				</form>
				</h1>
				<h1 class="h">
					<a data-transition="none" href="javascript:;" id="sellerListPage_score_btn">商家星级<span class="arrow"></span></a>
				</h1>
			
		</div>
		<!-- /header -->
		<div data-role="content">
			<div class="wrapper top">
				<div class="scroller">
					<div id="pullDown">
						<span class="pullDownIcon"></span><span class="pullDownLabel">下拉刷新...</span>
					</div>				
					<div class="boxList">
						<c:import url="sellerListAjax.jsp"/>
					</div>
					<div class="line"></div>
					<div id="pullUp">
						<span class="pullUpIcon"></span><span class="pullUpLabel">加载更多...</span>
					</div>
				</div>
			</div>


		</div>
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d">
			<c:import url="../footer.jsp"/>
		</div>			
		
		
	</div>
	<!-- SellerListPage end-->
	

</body>
</html>