<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
	<div data-role="page" id="addAddressPage">
		<div data-role="header" class="header_1 bg41AC98">
			<a data-transition="slide" href="#" data-role="button"
				data-rel="back" class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>		
			<h1 class="colorFFF">新增收货地址</h1>
			<a id="addressBtn" data-transition="slidefade" data-role="button" class="back bg41AC98 colorFFF">完成</a>
		</div>
		<div data-role="content">
			
			<div class="wrapper top">
				<div class="scroller">
					<form id="addressForm" action="${pageContext.request.contextPath}/user/addAddress" method="get" data-transition="slidefade">
						<input type="hidden" name="toUrl" value="${toUrl}">
						<div class="addressBox">
							<p><input type="text" name="receiverName" placeholder="收货人姓名"></p>
							<p><input type="text" name="receiverPhone" placeholder="收货人手机号码"></p>
							<p><input type="text" name="receiverCity" placeholder="收货人地区"></p>
							<p><input type="text" name="receiverAddress" placeholder="街道地址"></p>
							<p><input type="text" name="receiverZipCode" placeholder="邮编"></p>
						</div>
					</form>
				</div>
			</div>	
			
		</div>
		<c:import url="../footer.jsp"/>
	</div>	
	


	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/iscroll/iscroll.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>

</body>
</html>