<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %> 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	<div data-role="page" id="myOrdersPage">
		<div data-role="header" class="header_1 bg41AC98">
			<a  data-transition="slide" href="#" data-role="button" data-rel="back"
				class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>
			<h1 class="colorFFF">我的订单</h1>
		</div>
	
		<div data-role="content">

			<div class="wrapper top">
				<div class="scroller">
				
					<div class="orderBox">
					
						<c:forEach items="${list}" var="item">
							<div class="order">
								<div class="o_header">
									<a href="${pageContext.request.contextPath}/shop/showShop?id=${item.shop.id}" class="a1">
										<span class="s1"><img alt="" src="${pageContext.request.contextPath}/${item.shop.clogo}"></span>
										<span class="s2">${item.shop.cname}<span class="gt">&gt;</span></span>
										<span class="s3 red">交易成功</span>
									</a>
								</div>
								
								<c:forEach items="${item.orderItems}" var="item1">
									<div class="o_content">
										<a href="#" class="a2">
											<span class="s1"><img alt="" src="${pageContext.request.contextPath}/images/commodity/2095659570_78488880.310x310.jpg"></span>
											<span class="s2">${item1.cname}</span>
											<span class="s3">￥${item1.cprice}<br/>x${item1.buyNum}</span>
										</a>
									</div>
								</c:forEach>
								
								<div class="o_sum">
									<span>总1件商品，合计:<span class="red">30</span></span>
								</div>
								<div class="line"></div>
								<span class="o_option">
									<a class="a1" href="#">删除订单</a>
									<a class="a2" href="${pageContext.request.contextPath}/commodity/assess">评价</a>
								</span>
							</div>
						</c:forEach>
						
						<c:if test="${fn:length(list) <= 0}">
							<br>
							<p>
								您还没有下过订单，<a href="${pageContext.request.contextPath}/shop/list">立即搜索</a>店铺购买商品
							</p>
						</c:if>
					</div>
				
				</div>
			</div>
		</div>		
		
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d">
			
			<div data-role="navbar" class="myfooter bgEDEDED">
				<ul>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/main" class="ui-icon-index_1 ui-btn-active1">首页</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/map/map1Page" class="ui-icon-map_1">地图</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/buy/cart" class="ui-icon-purchase_1">进货单</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/user/userCenter" class="ui-icon-my_1">我的</a></li>
				</ul>
			</div>
		</div>
	</div>


</body>
</html>