<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/js/iscroll/scrollbar.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
<!-- 评价页面1 -->
	<!-- assessPage page start -->
	<div data-role="page" id="assessPage">
		<div data-role="header" class="header_1">
			<a  data-transition="none" href="#" data-role="button" data-rel="back"
				class="back" data-icon="arrow-l">&nbsp;</a>
			<h1>待评价订单</h1>
		</div>
		<!-- /header -->
		<div data-role="content">
			<div>
				<ul data-role="listview" data-inset="false">
					<li data-role="divider">深圳市大本钟贸易有限公司</li>
					<li><a  data-transition="none" href="#"> <img
							src="${pageContext.request.contextPath}/images/tmp/chrome.png">
							<h6>【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</h6>
							<p>29890.00￥ 数量:1</p>
					</a>
						<p class="p">
							<span class="red">29890.00</span> <a  data-transition="none"
								href="#" class="btn" data-shadow="false" data-role="button"
								data-mini="true" data-inline="true">查看物流</a> <a 
								data-transition="none" href="${pageContext.request.contextPath}/commodity/assess2" class="btn"
								data-shadow="false" data-role="button" data-mini="true"
								data-inline="true">评价</a>
						</p></li>
					<li data-role="divider">深圳市大本钟贸易有限公司</li>
					<li><a  data-transition="none" href="#"> <img
							src="${pageContext.request.contextPath}/images/tmp/firefox.png">
							<h2>Mozilla Firefox</h2>
							<p>Firefox is a web browser from Mozilla. Released in 2004.</p>
					</a>
						<p class="p">
							<span class="red">29890.00</span> <a  data-transition="none"
								href="#" class="btn" data-shadow="false" data-role="button"
								data-mini="true" data-inline="true">查看物流</a> <a 
								data-transition="none" href="${pageContext.request.contextPath}/commodity/assess2" class="btn" data-shadow="false"
								data-role="button" data-mini="true" data-inline="true">评价</a>
						</p></li>
				</ul>
			</div>
		</div>
		<c:import url="../footer.jsp"/>
	</div>
	<!-- assessPage page end -->

	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/iscroll/iscroll.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>

</body>
</html>