<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
	<!-- Product1Page 产品明细页面 start  -->
	<div data-role="page" id="CommodityPage">
		<div data-role="header" class="header_1"  data-tap-toggle="false" data-position="fixed">
			<a  data-transition="none" href="#" data-role="button" data-rel="back"
				class="back" data-icon="arrow-l">&nbsp;</a>
			<h1>宝贝明细</h1>
		</div>
		<!-- /header -->
		<div data-role="content">
			<div id="wrapper" class="top">
				<div id="scroller">
					<div class="p_img">
						<img alt="" src="${pageContext.request.contextPath}/${commodity.img}">
					</div>
		
					<div class="ui-grid-c onePrice0">
						<div class="ui-block-a">
							<span>【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</span>
						</div>
						<div class="ui-block-b">
							<img alt="" src="${pageContext.request.contextPath}/images/bg/star1.jpg"> <br> <span>收藏</span>
						</div>
						<div class="ui-block-b">
							<img alt="" src="${pageContext.request.contextPath}/images/bg/kefu.jpg"> <br> <span>客服</span>
						</div>
						<div class="ui-block-b">
							<img alt="" src="${pageContext.request.contextPath}/images/bg/fenxiang.jpg"> <br> <span>分享</span>
						</div>
					</div>
		
					<div class="ui-grid-a onePrice">
						<div class="ui-block-a s_1">
							<span>单价</span>
						</div>
						<div class="ui-block-b s_2">
							<span>￥29890.00</span>
						</div>
					</div>
		
					<div class="line"></div>
		
					<div class="ui-grid-b onePrice2">
						<div class="ui-block-a">
							<span class="s_1">成交 4笔</span>
						</div>
						<div class="ui-block-b">
							<span class="s_1">发货 广东水贝</span>
						</div>
						<div class="ui-block-c">
							<span class="s_1 s2">738人</span>
						</div>
					</div>
					<div class="tags" data-role="controlgroup" data-type="horizontal" data-mini="true">
						<a  class="a1" data-transition="none" href="#" data-role="button">产品详情</a> 
						<a  class="a2 on" data-transition="none" href="#" data-role="button">产品评价</a>
					</div>
					<div class="p_appraisal">
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
					</div>
					<div class="menu_height"></div>
					<div class="bottom_height"></div>
				</div>
		
			</div>
		</div>
		
		
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d" style="border-top:none;">

			<div class="btn">
				<a  class="a1" data-transition="none" href="${pageContext.request.contextPath}/buy/cart">加入进货单</a> 
					<a  class="a2" data-transition="none"
					href="#a_a" data-rel="popup" data-position-to="window">直接购买</a>
			</div>

			<div id="a_a" data-role="popup" data-theme="a">
				<div class="popup">
					<div class="ui-grid-a">
						<div class="ui-block-a">
							<img alt="" src="${pageContext.request.contextPath}/images/commodity/c_4.jpg">
						</div>
						<div class="ui-block-b">
							<span>【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</span> <br> <span>29890.00</span>
						</div>
					</div>
					<div class="nums">
						<span>购买数量：</span> <br>
						<br>
						<div>
							<div data-role="controlgroup" data-type="horizontal"
								data-mini="true" style="float:left;">
								<a  data-transition="none" href="#" data-role="button">-</a> <a 
									data-transition="none" href="#" data-role="button">100</a> <a 
									data-transition="none" href="#" data-role="button">+</a>
							</div>
							<div class="i_info">
								<span>库存96克拉</span>
							</div>
						</div>
					</div>
					<div class="clear"></div>
					<div class="line"></div>
					<div class="buyBtn">
						<a  class="a1" href="#confirmOrderPage">确定</a>
					</div>

				</div>
			</div>
			
			<div data-role="navbar" class="myfooter bgEDEDED">
				<ul>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/main" class="ui-icon-index_1 ui-btn-active1">首页</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/map/map1Page" class="ui-icon-map_1">地图</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/buy/cart" class="ui-icon-purchase_1">进货单</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/user/userCenter" class="ui-icon-my_1">我的</a></li>
				</ul>
			</div>
			
		</div>
	</div>
	<!-- Product1Page end  -->

	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/iscroll/iscroll.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>

</body>
</html>