<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
	<!-- Product1Page 产品明细页面 start  -->
	<div data-role="page" id="CommodityPage">
		<div data-role="header" class="header_1"  data-tap-toggle="false" data-position="fixed">
			<a  data-transition="slide" href="#" data-role="button" data-rel="back"
				class="back" data-icon="arrow-l">&nbsp;</a>
			<h1>宝贝明细</h1>
		</div>
		<!-- /header -->
		<div data-role="content">
			<div class="wrapper top">
				<div class="scroller">
					<div class="p_img">
						<img alt="" src="${pageContext.request.contextPath}/${commodity.img}">
					</div>
		
					<div class="ui-grid-c onePrice0">
						<div class="ui-block-a">
							<span>${commodity.name}</span>
						</div>
						<div class="ui-block-b">
							<img alt="" src="${pageContext.request.contextPath}/images/bg/star1.jpg"> <br> <span>收藏</span>
						</div>
						<div class="ui-block-b">
							<img alt="" src="${pageContext.request.contextPath}/images/bg/kefu.jpg"> <br> <span>客服</span>
						</div>
						<div class="ui-block-b">
							<img alt="" src="${pageContext.request.contextPath}/images/bg/fenxiang.jpg"> <br> <span>分享</span>
						</div>
					</div>
		
					<div class="ui-grid-a onePrice">
						<div class="ui-block-a s_1">
							<span>单价</span>
						</div>
						<div class="ui-block-b s_2">
							<span>${commodity.marketPrice}</span>
						</div>
					</div>
		
					<div class="line"></div>
		
					<div class="ui-grid-b onePrice2">
						<div class="ui-block-a">
							<span class="s_1">成交 4笔</span>
						</div>
						<div class="ui-block-b">
							<span class="s_1">发货 广东水贝</span>
						</div>
						<div class="ui-block-c">
							<span class="s_1 s2">738人</span>
						</div>
					</div>
					<div class="tags" data-role="controlgroup" data-type="horizontal" data-mini="true">
						<a  class="a1" data-transition="none" href="#" data-role="button">产品详情</a> 
						<a  class="a2 on" data-transition="none" href="#" data-role="button">产品评价</a>
					</div>
					<div class="p_appraisal">
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
						<div class="p_appraisal_line">
							<b>很好</b>
							<p>颜色分类：深紫色</p>
							<p>
								叶****2<span class="time">2015-06-03</span>
							</p>
						</div>
					</div>
					<div class="menu_height"></div>
					<div class="bottom_height"></div>
				</div>
		
			</div>
		</div>
		
		
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d" style="border-top:none;">

			<div class="btn">
				<a  class="a1" id="addCartBtn" data-transition="none" href="#addCartPopup" data-rel="popup" data-position-to="window">加入进货单</a> 
				<a  class="a2" id="goBuyBtn" data-transition="none" href="#addCartPopup" data-rel="popup" data-position-to="window">直接购买</a>
			</div>
			
			<div data-role="navbar" class="myfooter bgEDEDED">
				<ul>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/main" class="ui-icon-index_1 ui-btn-active1">首页</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/map/map1Page" class="ui-icon-map_1">地图</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/buy/cart" class="ui-icon-purchase_1">进货单</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/user/userCenter" class="ui-icon-my_1">我的</a></li>
				</ul>
			</div>
			
		</div>
		
		
			<div id="addCartPopup" data-role="popup" >
				<div class="popup">
					<form action="${pageContext.request.contextPath}/buy/addCart" id="cartForm" method="post">
						<div class="box">
							<div class="img">
								<img alt="" src="${pageContext.request.contextPath}/${commodity.img}">
							</div>
							<div class="info">
								<span class="s1">$123</span>
								<span class="s2">库存 126件</span>
								<span class="s3">已选 <span id="attr1ValShow">请选择</span> <span id="attr2ValShow"></span></span>
								<input type="hidden" value="${commodity.id}" name="cid"/>
								<input type="hidden" value="" id="buyTypeHid"/>
								<input type="hidden" id="attr1Val" name="attr1Val" tit="${commodity.attr1.name}" value=""/>
								<input type="hidden" id="attr2Val" name="attr2Val" tit="${commodity.attr2.name}" value=""/>
							</div>
						</div>
						<div class="line"></div>
						<div class="box">
							<span class="title">${commodity.attr1.name}</span>
							<div class="attr1">
								<c:forEach items="${commodity.attr1List}" var="item" varStatus="status">
									<a aid="${item[0]}" href="#">${item[1]}</a>
								</c:forEach>
							</div>
						</div>
						<div class="line"></div>
						<div class="box">
							<span class="title">${commodity.attr2.name}</span>
							<div class="attr2">
								<c:forEach items="${commodity.attr2List}" var="item" varStatus="status">
									<a aid="${item[0]}" href="#">${item[1]}</a>
								</c:forEach>
							</div>
						</div>
						<div class="line"></div>
						<div class="box">
							<span class="title inline">购买数量</span>
							<div class="number">
								<a href="#" class="a1" id="addNum">-</a>
								<input id="buyNum" name="buyNum" class="input" type="number" data-role="none" value="1"/>
								<a href="#" class="a2" id="revNum">+</a>
							</div>
						</div>
						<div class="line"></div>
						<div class="buyBtn">
							<a id="confirmOrderBtn" class="a1" href="#">确定</a>
						</div>
				
					</form>

				</div>
			</div>		
		
		
	</div>
	<!-- Product1Page end  -->

	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/iscroll/iscroll.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/cart.js"></script>

</body>
</html>