<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
<!-- confirmOrderPage 确认订单 start  -->
	<div data-role="page" id="confirmOrderPage">
		<div data-role="header" class="header_1">
			<a  data-transition="slide" href="#" data-role="button" data-rel="back"
				class="back" data-icon="arrow-l">&nbsp;</a>
			<h1>确认订单</h1>
			<a  data-transition="none" href="#userCenterCheckLoginPage" data-role="button" class="back">提交订单</a>
		</div>
		<!-- /header -->
		<div data-role="content">

			<div class="adds">
				<div class="line">&nbsp;</div>
				<h4>请填写你的收货地址</h4>
				<div class="line">&nbsp;</div>
			</div>
			
			
			<div class="plistBox">
				<p>货品清单</p>
				<div class="line"></div>
				<div class="ui-grid-b plist">
					<div class="ui-block-b p_0_1">
						<span>深圳市大本钟贸易有限...</span> |<span>优惠说明</span>
					</div>
					<div class="ui-block-c p_0_2"></div>

					<div class="ui-block-a p_1_0"></div>
					<div class="ui-block-b p_1_1">
						<img width="53" alt="" src="http://115.28.92.59:8089/simland-app-service/images/commodity/c_4.jpg">
					</div>
					<div class="ui-block-c p_1_2">
						<span>【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</span> <br> <span>￥29890.00</span>
					</div>
					<div class="ui-block-a p_2_0">&nbsp;</div>
					<div class="ui-block-b p_2_1">单价:￥29,890.00/克拉</div>
					<div class="ui-block-c p_2_2">
						<span class="s1">￥29,890.00</span><span class="s2">1克拉</span>
					</div>
				</div>
				<div class="ui-grid-b plist">
					<div class="ui-block-b p_0_1">
						<span>深圳市大本钟贸易有限...</span> |<span>优惠说明</span>
					</div>
					<div class="ui-block-c p_0_2"></div>

					<div class="ui-block-a p_1_0"></div>
					<div class="ui-block-b p_1_1">
						<img width="53" alt="" src="http://115.28.92.59:8089/simland-app-service/images/commodity/c_4.jpg">
					</div>
					<div class="ui-block-c p_1_2">
						<span>【十年资质】裸钻提供商 天然南非钻石 深圳水贝珠宝 一手...</span> <br> <span>￥29890.00</span>
					</div>
					<div class="ui-block-a p_2_0">&nbsp;</div>
					<div class="ui-block-b p_2_1">单价:￥29,890.00/克拉</div>
					<div class="ui-block-c p_2_2">
						<span class="s1">￥29,890.00</span><span class="s2">1克拉</span>
					</div>
				</div>
			</div>
			
			<div class="confirmOrderInfo_line">
			
			</div>
			
		</div>
		<div data-role="footer" data-tap-toggle="false" data-position="fixed"
			data-theme="d" style="border-top:none;">

			<div class="confirmOrderInfo">
				<div class="left">
					<p><span>店铺优惠:</span><span>￥0.00</span></p>
					<p><span>运费计算:</span><span>￥0.00</span></p>
					<p><span>货款总计:</span><span>￥29,890.00</span></p>
				</div>
				<div class="right">
					<div class="l1">
						<strong>总计:</strong>
						<span class="s1">￥29,890.00</span>
					</div>
					<div class="l2">
						<span>一种一件不含运费</span>
					</div>
					
				</div>
				<div class="clear"></div>
			</div>
			
			<div data-role="navbar" class="myfooter bgEDEDED">
				<ul>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/main" class="ui-icon-index_1 ui-btn-active1">首页</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/map/map1Page" class="ui-icon-map_1">地图</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/buy/cart" class="ui-icon-purchase_1">进货单</a></li>
					<li><a  data-transition="none" href="${pageContext.request.contextPath}/user/userCenter" class="ui-icon-my_1">我的</a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- confirmOrderPage end  -->

	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>

</body>
</html>