<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="A single-page template generated by MyEclipse Mobile Tools" />
	<title>Single-Page Application</title>
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
	<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
	<div data-role="page" id="auctionPage">
		<div data-role="header" class="header_1 bg41AC98">
			<a data-transition="slide" href="#" data-role="button" data-rel="back" class="back bg41AC98" data-icon="arrow-l">&nbsp;</a>
			<h1 class="colorFFF">水贝拍卖</h1>
		</div>
		<div data-role="content">
			<div class="wrapper top">
				<div class="scroller">
					<div class="auctionBox">
						<div class="video">
							<img alt="" src="${pageContext.request.contextPath}/images/tmp/auction_1_r2_c1.jpg">
						</div>
						<div class="tabs">
							<ul>
								<li><a href="#">拍品详情</a></li>
								<li><a href="#">报名</a></li>
							</ul>
						</div>
						<div class="msgBox">
							<div class="msg">
								<div class="u_msg">
									<div class="u_out">
										sdf
									</div>
								</div>
								<div class="u_img"><img alt="" src="${pageContext.request.contextPath}/images/user/auction_1_r6_c6.jpg"></div>
								<div class="clear"></div>				
							</div>
							<div class="msg">
								<div class="u_msg">
									<div class="u_out">
										sdf
									</div>
								</div>
								<div class="u_img"><img alt="" src="${pageContext.request.contextPath}/images/user/auction_1_r6_c6.jpg"></div>
								<div class="clear"></div>				
							</div>
							<div class="msg">
								<div class="u_msg">
									<div class="u_out">
										
									</div>
								</div>
								<div class="u_img"><img alt="" src="${pageContext.request.contextPath}/images/user/auction_1_r6_c6.jpg"></div>
								<div class="clear"></div>				
							</div>
						</div>
					</div>
					
					<div class="add_height">
						
					</div>
				</div>
			</div>	
		</div>
		
		<div data-role="footer" data-tap-toggle="false" data-cacheval="false" data-position="fixed" data-theme="d" style="border-top:none;">
			<div class="sendMsgBox">
				<a href="#" class="a1"></a>
				<input type="text" class="input1" />
				<a href="#" class="a2">出价</a>
			</div>
			<div data-role="navbar" class="myfooter bgEDEDED">
				<ul>
					<li><a data-transition="none" href="${pageContext.request.contextPath}/main" class="ui-icon-index_1 ui-btn-active1">首页</a></li>
					<li><a data-transition="none" href="${pageContext.request.contextPath}/map/map1Page" class="ui-icon-map_1">地图</a></li>
					<li><a data-transition="none" href="${pageContext.request.contextPath}/buy/cart" class="ui-icon-purchase_1">进货单</a></li>
					<li><a data-transition="none" href="${pageContext.request.contextPath}/user/userCenter" class="ui-icon-my_1">我的</a></li>
				</ul>
			</div>
		</div>
	</div>	

</body>
</html>