<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A single-page template generated by MyEclipse Mobile Tools" />

<title>Single-Page Application</title>

<link rel="stylesheet" href="${pageContext.request.contextPath}/css/jquery.mobile-1.4.3.css" />
<link rel="stylesheet" href="${pageContext.request.contextPath}/js/iscroll/scrollbar.css"  type="text/css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css" />

</head>

<body>
	
<!-- 登录页面 -->
	<!-- login page start -->
	<div data-role="page" id="loginPage">
		<div data-role="header" class="header_1 bg41AC98">
			<a data-transition="slide" href="#" data-role="button"
				data-rel="back" class="back bg41AC98 colorFFF" data-icon="arrow-l">&nbsp;</a>		
			<h1 class="colorFFF">登录</h1>
		</div>
		<div data-role="content">
			<div class="wrapper top">
				<div class="scroller">
					<div class="loginDiv">
						<form action="${pageContext.request.contextPath}/logindo" method="post" id="loginPage_form">
							<input type="text" name="uname" id="uname" value="zhuoer" placeholder="请输入手机号码">
							<input type="password" name="upw" id="upw" value="123123" placeholder="输入密码"> 
							<input type="hidden" name="toUrl" id="toUrl" value="/user/userCenter">
							<input type="submit" value="登录" id="loginBtn"/>
						</form>
						<br>
					</div>
					<div class="ui-grid-a bt">
						<div class="ui-block-a">
							<a  data-transition="none" href="#reg1Page">快速注册</a>
						</div>
						<div class="ui-block-b">
							<a  data-transition="none" href="#">找回密码</a>
						</div>
					</div>
				</div>
			</div>
				
		</div>
		<div data-role="footer" data-tap-toggle="false" data-position="fixed" data-theme="d">
			<c:import url="footer.jsp"/>
		</div>
	</div>
	<!-- login page end -->

	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.mobile-1.4.3.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/base.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/simland/app.js"></script>

</body>
</html>